
#debug: true

spring:
  profiles:
    include: prop

  codec:
    log-request-details: true
  mvc:
    log-request-details: true

logging:
    level:
        org:
            springframework:
                web: trace


