
#debug: true

spring:
  profiles:
    include: prop

  http:
    log-request-details: true

#  data:
#    mongodb:
#      host: 47.100.61.116
#      port: 27017
#      database: admin


#logging:
#    level:
#        org:
#            springframework:
#                web: debug