server:
    port: 8082

spring:
    application:
        name: eureka-consumer
eureka:
    instance:
        instance-id: eureka-consumer-8082
        prefer-ip-address: true # 访问路径可以显示 IP
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/  # 注册中心访问地址
